# ============================================================
# STRIPE PLANS — IHES NOM-035
# Todos los price_id de los productos en Stripe
# ============================================================

PLANS = {
    # ── NOM-035 ──────────────────────────────────────────────
    'nom035_micro_mensual': {
        'price_id': 'price_1TWKHAKv0IwwlafKRGi2WAn2',
        'name': 'NOM-035 Micro Mensual',
        'descripcion': 'Hasta 15 empleados',
        'precio': 599,
        'periodo': 'mensual',
        'modulo': 'nom035',
        'empleados_max': 15,
        'evaluaciones_mes': None,
    },
    'nom035_micro_semestral': {
        'price_id': 'price_1TWKaVKv0IwwlafKwTBfmVPf',
        'name': 'NOM-035 Micro Semestral',
        'descripcion': 'Hasta 15 empleados — 10% descuento',
        'precio': 3234,
        'periodo': 'semestral',
        'modulo': 'nom035',
        'empleados_max': 15,
        'evaluaciones_mes': None,
    },
    'nom035_micro_anual': {
        'price_id': 'price_1TWKauKv0IwwlafKK4LLpQ6v',
        'name': 'NOM-035 Micro Anual',
        'descripcion': 'Hasta 15 empleados — 20% descuento',
        'precio': 5750,
        'periodo': 'anual',
        'modulo': 'nom035',
        'empleados_max': 15,
        'evaluaciones_mes': None,
    },
    'nom035_pyme_mensual': {
        'price_id': 'price_1TWKLqKv0IwwlafKB24v7LnC',
        'name': 'NOM-035 PyME Mensual',
        'descripcion': 'Hasta 50 empleados',
        'precio': 1199,
        'periodo': 'mensual',
        'modulo': 'nom035',
        'empleados_max': 50,
        'evaluaciones_mes': None,
    },
    'nom035_pyme_semestral': {
        'price_id': 'price_1TWKbUKv0IwwlafK0q2eelhJ',
        'name': 'NOM-035 PyME Semestral',
        'descripcion': 'Hasta 50 empleados — 10% descuento',
        'precio': 6474,
        'periodo': 'semestral',
        'modulo': 'nom035',
        'empleados_max': 50,
        'evaluaciones_mes': None,
    },
    'nom035_pyme_anual': {
        'price_id': 'price_1TWKc9Kv0IwwlafKy0E41d62',
        'name': 'NOM-035 PyME Anual',
        'descripcion': 'Hasta 50 empleados — 20% descuento',
        'precio': 11510,
        'periodo': 'anual',
        'modulo': 'nom035',
        'empleados_max': 50,
        'evaluaciones_mes': None,
    },
    'nom035_empresarial_mensual': {
        'price_id': 'price_1TWKMHKv0IwwlafKNKMOuv2r',
        'name': 'NOM-035 Empresarial Mensual',
        'descripcion': 'Hasta 100 empleados',
        'precio': 1999,
        'periodo': 'mensual',
        'modulo': 'nom035',
        'empleados_max': 100,
        'evaluaciones_mes': None,
    },
    'nom035_empresarial_semestral': {
        'price_id': 'price_1TWKcaKv0IwwlafKDITHS4Sv',
        'name': 'NOM-035 Empresarial Semestral',
        'descripcion': 'Hasta 100 empleados — 10% descuento',
        'precio': 10794,
        'periodo': 'semestral',
        'modulo': 'nom035',
        'empleados_max': 100,
        'evaluaciones_mes': None,
    },
    'nom035_empresarial_anual': {
        'price_id': 'price_1TWKd1Kv0IwwlafKpHl9gx7Z',
        'name': 'NOM-035 Empresarial Anual',
        'descripcion': 'Hasta 100 empleados — 20% descuento',
        'precio': 19190,
        'periodo': 'anual',
        'modulo': 'nom035',
        'empleados_max': 100,
        'evaluaciones_mes': None,
    },

    # ── PSICOMETRÍA MENSUAL ───────────────────────────────────
    'psico_starter': {
        'price_id': 'price_1TWKN9Kv0IwwlafKPD1dMXFw',
        'name': 'Psicometría Starter',
        'descripcion': '10 evaluaciones por mes',
        'precio': 499,
        'periodo': 'mensual',
        'modulo': 'psicometria',
        'empleados_max': None,
        'evaluaciones_mes': 10,
    },
    'psico_pro_mensual': {
        'price_id': 'price_1TWKNUKv0IwwlafK13G9JXqd',
        'name': 'Psicometría Pro',
        'descripcion': '50 evaluaciones por mes',
        'precio': 999,
        'periodo': 'mensual',
        'modulo': 'psicometria',
        'empleados_max': None,
        'evaluaciones_mes': 50,
    },
    'psico_ilimitado_mensual': {
        'price_id': 'price_1TWKNmKv0IwwlafKxlFNdsxQ',
        'name': 'Psicometría Ilimitado Mensual',
        'descripcion': 'Evaluaciones ilimitadas',
        'precio': 1999,
        'periodo': 'mensual',
        'modulo': 'psicometria',
        'empleados_max': None,
        'evaluaciones_mes': -1,  # -1 = ilimitado
    },
    'psico_ilimitado_3meses': {
        'price_id': 'price_1TWKfqKv0IwwlafKtGggYmmW',
        'name': 'Psicometría Ilimitado 3 meses',
        'descripcion': 'Evaluaciones ilimitadas por 3 meses',
        'precio': 4999,
        'periodo': 'trimestral',
        'modulo': 'psicometria',
        'empleados_max': None,
        'evaluaciones_mes': -1,
    },
    'psico_ilimitado_anual': {
        'price_id': 'price_1TWKgeKv0IwwlafKvGFbIG4E',
        'name': 'Psicometría Ilimitado Anual',
        'descripcion': 'Evaluaciones ilimitadas por 12 meses',
        'precio': 14999,
        'periodo': 'anual',
        'modulo': 'psicometria',
        'empleados_max': None,
        'evaluaciones_mes': -1,
    },

    # ── PSICOMETRÍA CRÉDITOS (pago único) ─────────────────────
    'psico_creditos_10': {
        'price_id': 'price_1TWKeTKv0IwwlafKabW64ccA',
        'name': 'Psicometría Básico 10 eval',
        'descripcion': '10 evaluaciones — pago único',
        'precio': 1490,
        'periodo': 'unico',
        'modulo': 'psicometria',
        'empleados_max': None,
        'evaluaciones_mes': 10,
    },
    'psico_creditos_30': {
        'price_id': 'price_1TWKelKv0IwwlafK2GNOAtEW',
        'name': 'Psicometría Estándar 30 eval',
        'descripcion': '30 evaluaciones — pago único',
        'precio': 3490,
        'periodo': 'unico',
        'modulo': 'psicometria',
        'empleados_max': None,
        'evaluaciones_mes': 30,
    },
    'psico_creditos_100': {
        'price_id': 'price_1TWKf1Kv0IwwlafKdqabsJBm',
        'name': 'Psicometría Pro 100 eval',
        'descripcion': '100 evaluaciones — pago único',
        'precio': 8990,
        'periodo': 'unico',
        'modulo': 'psicometria',
        'empleados_max': None,
        'evaluaciones_mes': 100,
    },

    # ── SUITE ─────────────────────────────────────────────────
    'suite_pyme_mensual': {
        'price_id': 'price_1TWKOZKv0IwwlafKo98n1DsF',
        'name': 'Suite PyME Mensual',
        'descripcion': 'NOM-035 hasta 50 empleados + 20 evaluaciones/mes',
        'precio': 1499,
        'periodo': 'mensual',
        'modulo': 'suite',
        'empleados_max': 50,
        'evaluaciones_mes': 20,
    },
    'suite_pyme_anual': {
        'price_id': 'price_1TWKhFKv0IwwlafKFMhecM5z',
        'name': 'Suite PyME Anual',
        'descripcion': 'NOM-035 hasta 50 empleados + 20 evaluaciones/mes — anual',
        'precio': 18990,
        'periodo': 'anual',
        'modulo': 'suite',
        'empleados_max': 50,
        'evaluaciones_mes': 20,
    },
    'suite_pro_mensual': {
        'price_id': 'price_1TWKOsKv0IwwlafK7Qda06oA',
        'name': 'Suite Pro Mensual',
        'descripcion': 'NOM-035 hasta 100 empleados + evaluaciones ilimitadas',
        'precio': 2999,
        'periodo': 'mensual',
        'modulo': 'suite',
        'empleados_max': 100,
        'evaluaciones_mes': -1,
    },
    'suite_pro_anual': {
        'price_id': 'price_1TWKhmKv0IwwlafKZbSatWBY',
        'name': 'Suite Pro Anual',
        'descripcion': 'NOM-035 hasta 100 empleados + evaluaciones ilimitadas — anual',
        'precio': 34990,
        'periodo': 'anual',
        'modulo': 'suite',
        'empleados_max': 100,
        'evaluaciones_mes': -1,
    },
}

# Índice inverso: price_id → plan_key (útil en webhooks)
PRICE_ID_TO_PLAN = {v['price_id']: k for k, v in PLANS.items()}
