# Generated by Django 3.0.2 on 2020-01-27 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='access_code',
        ),
        migrations.AddField(
            model_name='workplace',
            name='record_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
