# Generated by Django 3.0.2 on 2020-01-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20200127_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='access_code',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Codigo de acceso'),
            preserve_default=False,
        ),
    ]
