# Generated by Django 3.0.2 on 2020-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_workplace_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(choices=[(0, '15-19'), (1, '20-24'), (2, '25-29'), (3, '30-34'), (4, '35-39'), (5, '40-44'), (6, '45-49'), (7, '50-54'), (8, '55-59'), (9, '60-64'), (10, '65-69'), (11, '70 o más')], default=1, verbose_name='Edad en años'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='civil_state',
            field=models.IntegerField(choices=[(0, 'Casado'), (1, 'Divorciado'), (2, 'Soltero'), (3, 'Viudo'), (4, 'Unión Libre')], verbose_name='Estado civil'),
        ),
    ]
