# Generated by Django 3.0.2 on 2020-02-21 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20200130_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Datos del Empleado', 'verbose_name_plural': 'Datos del Empleado'},
        ),
        migrations.AlterModelOptions(
            name='risksurveya',
            options={'verbose_name': 'Identificacion de analisis de los factores de riesgo psicosocial', 'verbose_name_plural': 'Identificacion de analisis de los factores de riesgo psicosocial'},
        ),
        migrations.AlterModelOptions(
            name='risksurveyb',
            options={'verbose_name': 'Identificacion de analisis de los factores de riesgo psicosocial', 'verbose_name_plural': 'Identificacion de analisis de los factores de riesgo psicosocial'},
        ),
        migrations.AlterModelOptions(
            name='traumasurvey',
            options={'verbose_name': 'Identificacion de trabajadores sujetos a traumas severos', 'verbose_name_plural': 'Identificacion de trabajadores sujetos a traumas severos'},
        ),
        migrations.AddField(
            model_name='risksurveya',
            name='record_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risksurveyb',
            name='record_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traumasurvey',
            name='record_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
