# Generated by Django 3.0.2 on 2020-02-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20200221_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='evaluation',
            field=models.IntegerField(default=1, verbose_name='Número de evaluación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risksurveya',
            name='evaluation',
            field=models.IntegerField(default=1, verbose_name='Número de evaluación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risksurveyb',
            name='evaluation',
            field=models.IntegerField(default=1, verbose_name='Número de evaluación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traumasurvey',
            name='evaluation',
            field=models.IntegerField(default=1, verbose_name='Número de evaluación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='evaluation',
            field=models.IntegerField(default=1, verbose_name='Número de evaluación'),
        ),
    ]
