# Generated by Django 3.0.2 on 2020-02-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20200221_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p10',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Ha tenido la impresión de que su vida se va a acortar, que va a morir antes que otras personas o que tiene un futuro limitado?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p11',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Ha tenido usted dificultades para dormir?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p12',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Ha estado particularmente irritable o le han dado arranques de coraje?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p13',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Ha tenido dificultad para concentrarse?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p14',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Ha estado nervioso o constantemente en alerta?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p15',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Se ha sobresaltado fácilmente por cualquier cosa?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p2',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Ha tenido recuerdos recurrentes sobre el acontecimiento que le provocan malestares?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p3',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Ha tenido sueños de carácter recurrente sobre el acontecimiento, que le producen malestar?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p4',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Se ha esforzado por evitar todo tipo de sentimientos, conversaciones o situaciones que le puedan recordar el acontecimiento?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p5',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Se ha esforzado por evitar todo tipo de actividades, lugares o personas que motivan recuerdos del acontecimiento?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p6',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Ha tenido dificultad para recordar alguna parte importante del evento?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p7',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Ha disminuido su interés en sus actividades cotidianas?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p8',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Se ha sentido usted alejado o distante de los demás?'),
        ),
        migrations.AlterField(
            model_name='traumasurvey',
            name='r1_p9',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí'), (1, 'No')], null=True, verbose_name='¿Ha notado que tiene dificultad para expresar sus sentimientos?'),
        ),
    ]
