# Generated by Django 3.0.2 on 2020-02-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20200225_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.AddField(
            model_name='userapp',
            name='workplaces_available',
            field=models.IntegerField(default=0, verbose_name='Centros pagados'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.IntegerField(choices=[(0, 'Por obra o proyecto'), (1, 'Por tiempo determinado (Temporal)'), (2, 'Por tiempo indeterminado'), (3, 'Por Horarios')], verbose_name='Tipo de contratación'),
        ),
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_products', to='surveys.Payment')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='surveys.Product')),
            ],
            options={
                'verbose_name': 'Producto comparado',
                'verbose_name_plural': 'Productos comparados',
                'ordering': ['-pk'],
            },
        ),
    ]
