# Generated by Django 3.0.2 on 2020-03-18 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0008_auto_20200228_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traumasurvey',
            options={'verbose_name': 'Acontecimientos traumáticos severos', 'verbose_name_plural': 'Acontecimientos traumáticos severos'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre y Apellidos'),
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last4', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('exp_month', models.IntegerField(verbose_name='Mes de expiración')),
                ('exp_year', models.IntegerField(verbose_name='Año de expiración')),
                ('brand', models.CharField(max_length=30, verbose_name='Marca')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('record_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('record_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjetas',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-pk'],
            },
        ),
    ]
