# Generated by Django 3.0.2 on 2020-03-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20200318_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='card_token',
            field=models.CharField(default='a', max_length=50, verbose_name='Token de tarjeta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userapp',
            name='client_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cliente conekta'),
        ),
    ]
