# Generated by Django 3.0.2 on 2020-03-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20200318_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcard',
            options={'ordering': ['-pk'], 'verbose_name': 'Tarjetas', 'verbose_name_plural': 'Tarjetas'},
        ),
        migrations.AddField(
            model_name='purchasedproducts',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_purchases', to='surveys.PaymentCard'),
        ),
    ]
