# Generated by Django 3.0.2 on 2020-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_auto_20200324_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='workplaces_availableB',
            field=models.IntegerField(default=0, verbose_name='Centros pagados B'),
        ),
        migrations.AddField(
            model_name='userapp',
            name='workplaces_availableC',
            field=models.IntegerField(default=0, verbose_name='Centros pagados C'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='workplaces_available',
            field=models.IntegerField(default=0, verbose_name='Centros pagados A'),
        ),
    ]
