# Generated by Django 3.0.2 on 2020-03-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_auto_20200324_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='evaluación pagada'),
            preserve_default=False,
        ),
    ]
