# Generated by Django 3.0.2 on 2020-09-16 16:55

from django.db import migrations, models
import django.db.models.deletion
import surveys.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_workplace_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField(verbose_name='Número de evaluación')),
                ('image', models.FileField(blank=True, null=True, upload_to=surveys.models.result_directory_path, verbose_name='Archivo')),
                ('record_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('result_type', models.IntegerField(choices=[(0, 'Informe de resultados ejecutivo'), (1, 'Informe de resultados detallado'), (2, 'Resultados del Instrumento para Identificar los Factores de Riesgo Psicosocial'), (3, 'Gantt de Actividades'), (4, 'Lista de Verificación de Evidencias de la NOM35'), (5, 'Propuesta de Política de Prevención de Riesgos Psicosociales')], verbose_name='Tipo de resultado')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_files', to='surveys.Workplace', verbose_name='Centro de trabajo')),
            ],
        ),
    ]
