# Generated by Django 3.0.2 on 2020-10-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_resultfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.IntegerField(choices=[(0, 'Por obra o proyecto'), (1, 'Por tiempo determinado'), (2, 'Por tiempo indeterminado (Temporal)'), (3, 'Por Horarios')], verbose_name='Tipo de contratación'),
        ),
    ]
