# Generated by Django 3.0.2 on 2020-11-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_auto_20201026_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='validated_email',
            field=models.BooleanField(default=False, verbose_name='Correo Validado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.IntegerField(choices=[(0, 'Por obra o proyecto'), (1, 'Por tiempo determinado'), (2, 'Por tiempo indeterminado (Temporal)'), (3, 'Por Honorarios')], verbose_name='Tipo de contratación'),
        ),
    ]
