# Generated by Django 3.0.2 on 2020-11-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_auto_20201103_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproducts',
            name='workplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='workplace_payments', to='surveys.Workplace', verbose_name='Centro de trabajo'),
            preserve_default=False,
        ),
    ]
