# Generated by Django 3.2.25 on 2026-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_perfil_narrativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.IntegerField(choices=[(0, 'Por obra o proyecto'), (1, 'Por tiempo determinado (Temporal)'), (2, 'Por tiempo indeterminado'), (3, 'Por Honorarios')], verbose_name='Tipo de contratación'),
        ),
    ]
