# Generated by Django 3.2.25 on 2026-05-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_alter_employee_contract_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom035_total', models.IntegerField(default=0)),
                ('nom035_used', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workplace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='surveys.workplace')),
            ],
        ),
    ]
