# Generated by Django 3.2.25 on 2026-06-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_userapp_psico_plan_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='nom035_demo',
            field=models.IntegerField(default=1, verbose_name='Créditos demo NOM-035'),
        ),
        migrations.AddField(
            model_name='userapp',
            name='psico_demo',
            field=models.IntegerField(default=1, verbose_name='Créditos demo psicometría'),
        ),
    ]
