# Generated by Django 3.2.25 on 2026-08-02 03:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0044_plan_accion_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Áreas / Departamentos'),
        ),
    ]
