# Generated by Django 3.2.25 on 2026-08-03 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0045_workplace_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código de referido')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('commission_pct', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Comisión (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('record_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso al panel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_key', models.CharField(blank=True, max_length=100, verbose_name='Plan')),
                ('monto_plan', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor del plan (MXN)')),
                ('monto_comision', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión (MXN)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('record_create', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='surveys.partner', verbose_name='Socio comercial')),
                ('referred_userapp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_generated', to='surveys.userapp', verbose_name='Cliente referido')),
            ],
            options={
                'ordering': ['-record_create'],
            },
        ),
        migrations.AddField(
            model_name='userapp',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_clients', to='surveys.partner', verbose_name='Referido por'),
        ),
    ]
