# Generated by Django 3.2.25 on 2026-08-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0046_partner_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercommission',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Invoice ID'),
        ),
        migrations.AddField(
            model_name='partnercommission',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Venta inicial'), ('renovacion', 'Renovación')], default='venta', max_length=20, verbose_name='Tipo'),
        ),
    ]
