# Generated by Django 3.2.25 on 2026-08-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0047_partner_commission_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='commission_pct',
        ),
    ]
